### ISSUE TITLE
Fix animations links

### ISSUE THREAD

**Issue by NawfelBgh** [struct-animate/struct-animate.github.io#6]
- /js/Animations/pile/pile.html
- /js/Animations/tab/les tableaux Non-Tries.html
- /js/Animations/tab/les tableaux Tries.html
- ...

**Comment by omar-kada** [comment]
the problem is with capital letters, 
the files are named 
- "Pile.html" not "pile.html"
- "Les Tableaux Non-Tries.html" not "les tableaux Non-Tries.html"
  ...
